classdef tBoxPanel < utilities.mixin.PanelTests
    %TBOXPANEL Tests for uix.BoxPanel.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uix.BoxPanel'}
        % Name-value pair input arguments to use when testing the component
        % constructor.
        ConstructorInputArguments = {{
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Tag', 'Test', ...
            'Visible', 'on', ...
            'BorderType', 'none', ...
            'FontAngle', 'normal', ...
            'FontName', 'SansSerif', ...
            'FontSize', 20, ...
            'FontUnits', 'points', ...
            'FontWeight', 'bold'
            }}
        % Name-value pairs to use when testing the component's get and set
        % methods.
        GetSetNameValuePairs = {{
            'BackgroundColor', [1, 1, 0], ...
            'Minimized', false, ...
            'Docked', true, ...
            'DockFcn', @utilities.noop, ...
            'DockTooltipString', 'dock', ...
            'MaximizeTooltipString', 'maximize', ...
            'MinimizeFcn', @utilities.noop, ...
            'MinimizeTooltipString', 'minimize', ...
            'HelpFcn', @utilities.noop, ...
            'HelpTooltipString', 'help', ...
            'UndockTooltipString', 'undock', ...
            'BorderType', 'line', ...
            'BorderWidth', 10, ...
            'Title', 'uix.BoxPanel Test', ...            
            'ForegroundColor', [1, 1, 1], ...
            'HighlightColor', [1, 0, 1], ...
            'ShadowColor', [0, 0, 0], ...
            'CloseRequestFcn', @utilities.noop, ...
            'CloseTooltipString', 'close', ...
            'FontAngle', 'italic'
            }}
    end % properties ( TestParameter )

    methods ( Test, Sealed )

    end % methods ( Test, Sealed )

end % class