classdef tBoxPanel < utilities.mixin.BoxPanelTests
    %TBOXPANEL Tests for uix.BoxPanel.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uix.BoxPanel'}
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'BackgroundColor', [1, 1, 0], ...
            'BorderType', 'line', ...
            'BorderWidth', 2, ...
            'CloseRequestFcn', @utilities.noop, ...
            'CloseTooltipString', 'Close', ...
            'DeleteFcn', @utilities.noop, ...
            'Docked', false, ...
            'DockFcn', @utilities.noop, ...
            'DockTooltipString', 'Dock', ...
            'FontAngle', 'italic', ...
            'FontName', 'SansSerif', ...
            'FontUnits', 'pixels', ...
            'FontSize', 20, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0, 0, 1], ...
            'HelpFcn', @utilities.noop, ...
            'HelpTooltipString', 'Help', ...
            'HighlightColor', [1, 0, 1], ...
            'MaximizeTooltipString', 'Maximize', ...
            'Minimized', false, ...
            'MinimizeFcn', @utilities.noop, ...
            'MinimizeTooltipString', 'Minimize', ...
            'Padding', 5, ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Tag', 'Test', ...
            'Title', 'uiextras.BoxPanel Test', ...
            'TitleColor', [1, 0, 0], ...
            'UndockTooltipString', 'Undock', ...
            'Visible', 'on'
            }}
    end % properties ( TestParameter )

end % class