classdef tGridFlex < utilities.mixin.SharedGridTests & ...
        utilities.mixin.SharedFlexTests
    %TGRIDFLEX Tests for uix.GridFlex.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uix.GridFlex'}
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'BackgroundColor', [0, 0, 1], ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...            
            'DividerMarkings', 'off', ...
            'Spacing', 5, ...
            'Tag', 'test' ...
            'Visible', 'on', ...
            'Widths', double.empty( 0, 1 ), ...
            'Heights', double.empty( 0, 1 ), ...
            'MinimumWidths', double.empty( 0, 1 ), ...
            'MinimumHeights', double.empty( 0, 1 )
            }}
    end % properties ( TestParameter )

    properties ( Constant )
        % Grid dimension name-value pairs used when testing the component's
        % get/set methods.
        GridDimensionNameValuePairs = {
            'Heights', [-10, -1, 20], ...
            'Widths', [-0.5, 50], ...
            'MinimumHeights', [2, 2, 2], ...
            'MinimumWidths', [2, 2]
            }
    end % properties ( Constant )

end % class