classdef tTabPanel < utilities.mixin.TabPanelTests
    %TTABPANEL Tests for uix.TabPanel.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uix.TabPanel'}
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Tag', 'Test', ...
            'Visible', 'on', ...
            'FontAngle', 'italic', ...
            'FontName', 'SansSerif', ...            
            'FontUnits', 'centimeters', ...
            'FontSize', 0.5, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1, 1, 0], ...
            'TabTitles', cell.empty( 0, 1 ), ...
            'TabEnables', cell.empty( 0, 1 ), ...
            'TabLocation', 'bottom', ...
            'TabWidth', 100, ...
            'ForegroundColor', [1, 1, 1], ...
            'HighlightColor', [1, 0, 1], ...
            'ShadowColor', [0, 0, 0], ...
            }}
    end % properties ( TestParameter )

end % class