classdef PanelTests < utilities.mixin.SharedPanelTests
    %PANELTESTS Tests common to panels.

    properties ( TestParameter )
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'BackgroundColor', [1, 1, 0], ...
            'BorderType', 'line', ...
            'ButtonDownFcn', @utilities.noop, ...
            'CreateFcn', @utilities.noop, ...
            'ContextMenu', [], ...
            'DeleteFcn', @utilities.noop, ...
            'Enable', 'on', ...
            'FontAngle', 'normal', ...
            'FontName', 'SansSerif', ...
            'FontSize', 20, ...
            'FontUnits', 'points', ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0, 0, 0], ...            
            'HighlightColor', [1, 1, 1], ...
            'HandleVisibility', 'on', ...
            'Padding', 5, ...
            'Tag', 'Test', ...             
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Visible', 'on'
            }}
    end % properties ( TestParameter )

end % class