classdef tGrid < GridTests & ContainerSharedTests
    %TGRID Tests for uiextras.Grid.

    properties ( TestParameter )
        % The container type (constructor name).
        ContainerType = {'uiextras.Grid'}
        % Name-value pairs to use when testing the get/set methods.
        GetSetArgs = {{
            'RowSizes', [-10, -1, 20], ...
            'ColumnSizes', [-0.5, 50], ...
            'MinimumRowSizes', [1, 1, 1], ...
            'MinimumColumnSizes', [2, 2]
            }}
        % Name-value pairs to use when testing the constructor.
        ConstructorArgs = {{
            'BackgroundColor', [0, 0, 1], ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Spacing', 5, ...
            'Tag', 'test' ...
            'Visible', 'on'
            }}
    end % properties ( TestParameter )

end % class

