classdef tHButtonBox < utilities.mixin.ContainerTests
    %THBUTTONBOX Tests for uiextras.HButtonBox.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uiextras.HButtonBox'}
        % Name-value pair input arguments to use when testing the component
        % constructor.
        ConstructorInputArguments = {{
            'BackgroundColor', [0, 0, 1], ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Spacing', 5, ...
            'Tag', 'test', ...
            'Visible', 'on', ...
            'ButtonSize', [200, 25]
            }}
        % Name-value pairs to use when testing the component's get and set
        % methods.
        GetSetNameValuePairs = {{
            'BackgroundColor', [0, 1, 0], ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'top'
            }}
    end % properties ( TestParameter )

end % class