classdef tPanel < PanelTests & ContainerSharedTests
    %TPANEL Tests for uiextras.Panel.

    properties ( TestParameter )
        % The container type (constructor name).
        ContainerType = {'uiextras.Panel'}
        % Name-value pairs to use when testing the get/set methods.
        GetSetArgs = {{
            'BackgroundColor', [1, 1, 0]
            }}
        % Name-value pairs to use when testing the constructor.
        ConstructorArgs = {{
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Tag', 'Test', ...
            'Visible', 'on', ...
            'FontAngle', 'normal', ...
            'FontName', 'SansSerif', ...
            'FontSize', 20, ...
            'FontUnits', 'points', ...
            'FontWeight', 'bold'
            }}
    end % properties ( TestParameter )

end % class