classdef tTabPanel < utilities.mixin.TabPanelTests
    %TTABPANEL Tests for uiextras.TabPanel.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uiextras.TabPanel'}
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Tag', 'Test', ...
            'Visible', 'on', ...
            'FontAngle', 'italic', ...
            'FontName', 'SansSerif', ...
            'FontUnits', 'centimeters', ...
            'FontSize', 0.5, ...            
            'FontWeight', 'bold', ...
            'BackgroundColor', [1, 1, 0], ...
            'TabNames', cell.empty( 1, 0 ), ...
            'TabEnable', cell.empty( 1, 0 ), ...
            'TabPosition', 'top', ...
            'TabSize', 50, ...
            'ForegroundColor', [1, 1, 1], ...
            'HighlightColor', [1, 0, 1], ...
            'ShadowColor', [0, 0, 0], ...
            }}
    end % properties ( TestParameter )

end % class