classdef tVButtonBox < ContainerSharedTests
    %TVBUTTONBOX Tests for uiextras.VButtonBox.

    properties ( TestParameter )
        % The container type (constructor name).
        ContainerType = {'uiextras.VButtonBox'}
        % Name-value pairs to use when testing the get/set methods.
        ConstructorArgs = {{
            'BackgroundColor', [0, 0, 1], ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Spacing', 5, ...
            'Tag', 'test', ...
            'Visible', 'on', ...
            'ButtonSize', [200, 25]
            }}
        % Name-value pairs to use when testing the constructor.
        GetSetArgs  = {{
            'BackgroundColor', [0, 1, 0], ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'top'
            }}
    end % properties ( TestParameter )

end % class