classdef tVButtonBox < utilities.mixin.SharedContainerTests
    %TVBUTTONBOX Tests for uiextras.VButtonBox.

    properties ( TestParameter )
        % The constructor name, or class, of the component under test.
        ConstructorName = {'uiextras.VButtonBox'}
        % Name-value pair arguments to use when testing the component's
        % constructor and get/set methods.
        NameValuePairs = {{
            'BackgroundColor', [0, 0, 1], ...
            'Units', 'pixels', ...
            'Position', [10, 10, 400, 400], ...
            'Padding', 5, ...
            'Spacing', 5, ...
            'Tag', 'test', ...
            'Visible', 'on', ...
            'ButtonSize', [200, 25], ...
            'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'top'
            }}
    end % properties ( TestParameter )

end % class