classdef PanelTests < matlab.unittest.TestCase
    %TPANELS Summary of this class goes here
    %   Detailed explanation goes here
    
%     properties (TestParameter)
%         ContainerType   = {'uiextras.Panel', 'uiextras.CardPanel', 'uiextras.TabPanel', 'uiextras.BoxPanel'};
%         SelectablePanel = {'uiextras.Panel', 'uiextras.CardPanel', 'uiextras.TabPanel'};
%         GetSetPVArgs = {
%             {'uiextras.Panel', 'BackgroundColor', [1 1 0]}
%             {'uiextras.CardPanel', 'BackgroundColor', [1 1 0], 'SelectedChild', 2}
%             {'uiextras.TabPanel', ...
%              'BackgroundColor',     [1 1 0], ...
%              'SelectedChild',       2, ...
%              'TabNames',            {'Tab 1', 'Tab 2', 'Tab 3'}, ...
%              'TabEnable',           {'on', 'off', 'on'}, ...
%              'TabPosition',         'bottom', ...
%              'TabSize',             10, ...
%              'ForegroundColor',     [1 1 1], ...
%              'HighlightColor',      [1 0 1], ...
%              'ShadowColor',         [0 0 0]
%              }
%             {'uiextras.BoxPanel', ...
%             'BackgroundColor',  [1 1 0], ...
%             'IsMinimized',      false, ...
%              'IsDocked',        true, ...
%              'BorderType',      'etchedout', ...
%              'BorderWidth',     10, ...
%              'Title',           'box panel test', ...
%              'TitleColor',      [1 0 0], ...
%              'ForegroundColor', [1 1 1], ...
%              'HighlightColor',  [1 0 1], ...
%              'ShadowColor',     [0 0 0]
%              }
%             };
%         SpecialConstructionArgs = {
%             {'uiextras.Panel', ...
%              'FontAngle',   'normal', ...
%              'FontName',    'Arial', ...
%              'FontSize',    20, ...
%              'FontUnits',   'points', ...
%              'FontWeight',  'bold'
%              }
%             {'uiextras.CardPanel'}
%             {'uiextras.TabPanel', ...
%              'FontAngle',   'normal', ...
%              'FontName',    'Arial', ...
%              'FontSize',    20, ...
%              'FontUnits',   'points', ...
%              'FontWeight',  'bold'
%              }
%             {'uiextras.BoxPanel', ...
%              'BorderType', 'etchedout', ...
%              'FontAngle',   'normal', ...
%              'FontName',    'Arial', ...
%              'FontSize',    20, ...
%              'FontUnits',   'points', ...
%              'FontWeight',  'bold'
%              }
%             };
%     end
%     
%     properties
%         DefaultConstructionArgs = {
%             'Parent',          gcf(), ...
%             'Units',           'pixels', ...
%             'Position',        [10 10 400 400], ...
%             'Padding',         5, ...
%             'Tag',             'Test', ...
%             'Visible',         'on', ...
%             };
%     end
    
    methods (Test)
        
        function testLayoutInPanel(testcase, ContainerType)
            %testLayoutInTab  Test layout in panel
            obj = testcase.hCreateObj(ContainerType, {'Parent', gcf()});
            
            b = uiextras.HBox( 'Parent', obj );
            testcase.verifyEqual( obj.Contents, b );
        end

    end
    
end

