classdef tCardPanel < ContainerSharedTests ...
        & PanelTests
    %TCARDPANEL unit tests for uiextras.CardPanel
    
    properties (TestParameter)
        ContainerType   = {'uiextras.CardPanel'};
        GetSetArgs = {
            {'BackgroundColor', [1 1 0], ...
            'SelectedChild',   2 ...
            }};
        ConstructorArgs = {
            {'Units',           'pixels', ...
            'Position',        [10 10 400 400], ...
            'Padding',         5, ...
            'Tag',             'Test', ...
            'Visible',         'on', ...
            }};
    end
    
end