classdef tGridFlex < ContainerSharedTests ...
                   & GridTests ...
%TGRIDFLEX unit tests for uiextras.GridFlex

properties (TestParameter)
    ContainerType   = {'uiextras.GridFlex'};
    GetSetArgs = {
       {'RowSizes',        [-0.5, 50], ...
        'ColumnSizes',     [-10, -1, 20], ...
        'MinimumWidths',   [1; 1; 1], ...
        'MinimumHeights',  2 ...
        }};
    ConstructorArgs = {
       {'BackgroundColor', [0 0 1], ...
        'Units',           'pixels', ...
        'Position',        [10 10 400 400], ...
        'Padding',         5, ...
        'Spacing',         5, ...
        'Tag',             'test' ...
        'Visible',         'on', ...
        'ShowMarkings',    'on' ...
        }};
end

end

