classdef tGrid < ContainerSharedTests ...
                & GridTests
%TGRID unit tests for uiextras.Grid

properties (TestParameter)
    ContainerType   = {'uiextras.Grid'};
    GetSetArgs = {
       {'RowSizes',        [-10; -1; 20], ...
        'ColumnSizes',     [-0.5; 50], ...
        'MinimumRowSizes', [1; 1; 1], ...
        'MinimumColumnSizes', [2; 2] ...
        }};
    ConstructorArgs = {
       {'BackgroundColor', [0 0 1], ...
        'Units',           'pixels', ...
        'Position',        [10 10 400 400], ...
        'Padding',         5, ...
        'Spacing',         5, ...
        'Tag',             'test' ...
        'Visible',         'on', ...
        }};
end

end

