classdef tGrid < ContainerSharedTests ...
                & GridTests ...
%TGRID unit tests for uiextras.Grid

properties (TestParameter)
    ContainerType   = {'uiextras.Grid'};
    GetSetArgs = {
       {'RowSizes',        [-0.5; 50], ...
        'ColumnSizes',     [-10; -1; 20], ...
        'MinimumRowSizes',  2, ...
        'MinimumColumnSizes',   [1; 1; 1] ...
        }};
    ConstructorArgs = {
       {'BackgroundColor', [0 0 1], ...
        'Units',           'pixels', ...
        'Position',        [10 10 400 400], ...
        'Padding',         5, ...
        'Spacing',         5, ...
        'Tag',             'test' ...
        'Visible',         'on', ...
        }};
end

end

