classdef tHButtonBox < ContainerSharedTests
    %THBUTTONBOX Unit tests for uiextras.HButtonBox and uiextras.VButtonBox.
    % sets ButtonBox specific parameters for ContainerSharedTests. 
    
     properties (TestParameter)
        ContainerType = {'uiextras.HButtonBox'};
        ConstructorArgs = {
           {'BackgroundColor', [0 0 1], ...
            'Units',           'pixels', ...
            'Position',        [10 10 400 400], ...
            'Padding',         5, ...
            'Spacing',         5, ...
            'Tag',             'test', ...
            'Visible',         'on', ...
            'ButtonSize',      [200 25] ...
            }};
        GetSetArgs  = {
            {'BackgroundColor',     [0 1 0], ...
            'HorizontalAlignment',  'right', ...
            'VerticalAlignment',    'top' ...
            }};
     end

end

